version: "3.9"

services:
  lbc-api:
    build:
      context: .
      target: dev
    container_name: lbc-api
    ports:
      - 8000:8000
    volumes:
      - ./:/go/lbc-api
    env_file:
      - configuration/env/dev.env