version: "3.9"

services:
  db_test:
    image: mysql:8.0
    container_name: lbc-api_db
    ports:
      - "3307:3306"
    restart: always
    env_file:
      - configuration/env/dev.env
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: 'lbc-api_test'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10


  lbc-api:
    build:
      context: .
      target: dev
    container_name: lbc-api
    ports:
      - 8000:8000
    volumes:
      - ./:/go/lbc-api
    env_file:
      - configuration/env/dev.env
    environment:
      MYSQL_DATABASE: 'lbc-api_test'
      MYSQL_HOST: 'db_test'
    entrypoint: ['go', 'test', './...']
    depends_on:
      db_test:
        condition: service_healthy